### ISSUE TITLE
Pronounciation?

### ISSUE THREAD

**Issue by abbyaha** [brianjp07/brewhaha#2]
Is it brewHAha or BREWhaha?!?!?!

I need to know

**Comment by teaganstrayed** [comment]
The latter lol. Like MUhaha :p
- Vest

On Fri, May 8, 2015 at 2:42 PM, brianjp07/brewhaha reply@reply.github.com wrote:

Is it brewHAha or BREWhaha?!?!?!

I need to know

##

**Comment by abbyaha** [comment]
Knew it
